### ISSUE TITLE
Should bring up to date with recent release of Sphinx v2.0

### ISSUE THREAD

**Issue by ViktorHaag** [markstory/sphinxcontrib-phpdomain#21]
This domain leans on a localization function that's become deprecated with Sphinx v2.0. It would be useful to bring it up to date with respect to Sphinx v2.0.

**Comment by ViktorHaag** [comment]
Thanks for merging the PR, @markstory -- I think this issue is still open, however -- the wheel up on PyPi may be built only for Py2, and so Py3 users can't get to it as the latest release. Installing from the source tarball downloadable from GitHub does, however, work as a work around. Could you add a source distribution, or a wheel built for Python 3, to PyPi? Thanks!

**Comment by markstory** [comment]
I've published an sdist and universal wheel now.
