### ISSUE TITLE
Tagged releases needed for 0.6.0 (and 0.6.1?)

### ISSUE THREAD

**Issue by ViktorHaag** [markstory/sphinxcontrib-phpdomain#25]
Hey @markstory -- currently on PyPi we have a release package for 0.6.0, but we don't have a release tag for that code here in the repo and we probably should.

Also -- since you've merged in https://github.com/markstory/sphinxcontrib-phpdomain/pull/24, it might be a good idea to generate a tag for that at 0.6.1 (and maybe roll a package for PyPi)?

**Comment by markstory** [comment]
I've added a tag for the 0.6.1 release and pushed packages. I think the commit for the 0.6.0 release might be stranded on another machine. It likely won't be able to be pushed now.
