### ISSUE TITLE
have sphinx 2.2.0 which is incompatible message

### ISSUE THREAD

**Issue by panosru** [markstory/sphinxcontrib-phpdomain#26]
Hello, when I run `pip3 install -U sphinx` I'm getting the following:

```
ERROR: sphinxcontrib-phpdomain 0.6.1 has requirement sphinx<2.2,>=1.3, but you'll have sphinx 2.2.0 which is incompatible.
Installing collected packages: sphinx
Successfully installed sphinx-2.2.0
```

Could you please let me know how to fix that? 

Thanks! :)

**Comment by markstory** [comment]
The current version constraint has <2.2 as that was the last version I ran tests on. I've bumped it up and released 0.6.2
