### ISSUE TITLE
Supported Version of Sphinx

### ISSUE THREAD

**Issue by noctua84** [markstory/sphinxcontrib-phpdomain#30]
Requirements.txt mentions that Sphinx is only supported until less than 2.5
The current Sphinx-release is 3.1.

Updating requirements/checking compatibility would be needed.

**Comment by markstory** [comment]
Yes, I've not yet had time to upgrade to sphinx 3. Any chance you'd be willing to help with that?

**Comment by noctua84** [comment]
Willing won't be the hindering thing, but honestly, I don't have any idea what do to, because this would be the first time doing so for me.

**Comment by markstory** [comment]
> I mean, I could simply modify the requirements.txt and check if it works or breaks :)

That is where I would start too.
