### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by stevespages** [markstory/sphinxcontrib-phpdomain#41]
In your **PHP Domain for Sphinx** documentation you show some source code (This is source:). Then you show **Result**.  Both of these look identical. I am assuming you meant to show something different for **Result** as what you have shown looks like source ie. reStructuredText

**Comment by stevespages** [comment]
I have just seen your documentation at https://pythonhosted.org/sphinxcontrib-phpdomain/ where the **Result** looks great. So, it is just a problem with the GitHub page.

**Comment by markstory** [comment]
>  So, it is just a problem with the GitHub page.

I'm not sure there is much I can do about that without causing problems in other places the documentation is published.

**Comment by n-peugnet** [comment]
Maybe the example should only be in the doc and not in the README, as it will always be broken outside of a Sphinx doc with phpdomain enabled. The README could only provide a link to the corresponding page of the doc.

**Comment by markstory** [comment]
Leaving the rendered examples out of the README sounds reasonable to me.
