### ISSUE TITLE
Online HTML documentation is not up to date

### ISSUE THREAD

**Issue by n-peugnet** [markstory/sphinxcontrib-phpdomain#45]
The online docs <https://pythonhosted.org/sphinxcontrib-phpdomain/> does not seem to be built anymore. It is not up to date (see [ChangeLog section](https://pythonhosted.org/sphinxcontrib-phpdomain/#changelog))

I found this information with a quick search <https://wiki.python.org/moin/PyPiDocumentationHosting>:

> http://pythonhosted.org/ (formerly http://packages.python.org/ ) used to provide hosting for documentation for Python packages; this [is no longer the case](https://github.com/pypa/warehouse/issues/509) and Python project developers should instead use [Read the Docs](https://readthedocs.org/).

I never used ReadTheDocs but if you want I can provide you a GitHub action workflow to build and publish your docs on GitHub pages, as you already use it for CI and [I did one for myself](https://github.com/club-1/sphinx-inventory-parser/blob/main/.github/workflows/docs.yml) some days ago.

**Comment by markstory** [comment]
Publishing to github pages seems like a good solution for this project. A pull request would be greatly appreciated.
