### ISSUE TITLE
iteritems has been renamed to items in python3

### ISSUE THREAD

**Issue by automactic** [markstory/sphinxcontrib-phpdomain#5]
Hi, I was trying to build some php docs using sphinx. I noticed dict.iteritems() are still used, causing build to fail. Would you please fix it? Thanks!

**Comment by markstory** [comment]
Could you send a pull request? I don't use python 3.

**Comment by juliushaertl** [comment]
Looks like this is already fixed with cd0dd7276f48499f3b37d37c0b3e0ed809843ee1
