### ISSUE TITLE
Latest release is broken with old python

### ISSUE THREAD

**Issue by mvorisek** [markstory/sphinxcontrib-phpdomain#54]
It seems https://github.com/markstory/sphinxcontrib-phpdomain/commit/991e3f14341ed453a5cfe41c139ff8d49d5032b0 has broken build with old python.

repro log: https://readthedocs.org/projects/agile-core/builds/20132718/ (see https://readthedocs.org/projects/agile-core/builds/ for previously passing build logs)

with `sphinxcontrib-phpdomain==0.9.0` the build is passing

Can be solved by upgrading Python to v3, but v2 should still be supported, as many projects use it.

**Comment by markstory** [comment]
> but v2 should still be supported, as many projects use it.

Sorry, you'll have to pin to an older release if you want to use Python 2.x.
