### ISSUE TITLE
Namespace not recognized in :php:class:`\atk4\ui\Form`.

### ISSUE THREAD

**Issue by romaninsh** [markstory/sphinxcontrib-phpdomain#6]
While from inside the deeper namespace I find it difficult to reference another class:

``` rst
.. php:namespace:: atk4\ui\FormField

See :php:class:`\atk4\ui\Form`.
```

Produces errer: reference target not found: atk4uiForm.

**Comment by markstory** [comment]
You need to double up your \ characters in the backticks. This is something that rst syntax requires unfortunately.
