### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by tenzap** [markstory/sphinxcontrib-phpdomain#64]
While working on trying to make sphinxcontrib-phpdomain 0.11.0 enter Debian repository, the need for clarification of the license was raised by the Debian FTP team who is responsible for these verifications.

For instance:
- `LICENSE` file refers to `AUTHORS` file, but I couldn't find that file.
- `sphinxcontrib\__init__.py` mentions the Sphinx team as copyright holder and refers
to a probably different `AUTHORS` file.

Could you please clarify these and release a new version once fixed?

**Comment by markstory** [comment]
Thanks for the interest in getting this published to debian. I've aligned all the license metadata to reflect this project's history and callbacks to the sphinx code it was started from.
